{
  "formatVersion": "1.1",
  "component": {
    "group": "com.james",
    "module": "libraryA",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nbvmj2vzlbdglgmo6p5amqpeva"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraryA-1.3.aar",
          "url": "libraryA-1.3.aar",
          "size": 23429,
          "sha512": "1e9a8be25a4a87effe1aaf2860e9393c54c11ab1ee26ff19e02da990b047b6f2165b483be9781a03cf029ae901f48bee6a831fe9cf73502bcaf4a33137f4cc55",
          "sha256": "530df9e84dd559e4db66a947eb39670947d59c3b23936a7872978a4aaaac8b7f",
          "sha1": "02c5015b013e81bbd1cb2b225d41cecce94c0a80",
          "md5": "b481008a5282444f1622ba00dad3a7d6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraryA-1.3.aar",
          "url": "libraryA-1.3.aar",
          "size": 23429,
          "sha512": "1e9a8be25a4a87effe1aaf2860e9393c54c11ab1ee26ff19e02da990b047b6f2165b483be9781a03cf029ae901f48bee6a831fe9cf73502bcaf4a33137f4cc55",
          "sha256": "530df9e84dd559e4db66a947eb39670947d59c3b23936a7872978a4aaaac8b7f",
          "sha1": "02c5015b013e81bbd1cb2b225d41cecce94c0a80",
          "md5": "b481008a5282444f1622ba00dad3a7d6"
        }
      ]
    }
  ]
}
