{
  "formatVersion": "1.1",
  "component": {
    "group": "com.james",
    "module": "libraryB",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xehlucscfbgb3cdnxpsyxjp5bq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraryB-1.2.aar",
          "url": "libraryB-1.2.aar",
          "size": 23421,
          "sha512": "5bcb453c56dc159e37a1e0804f22175961786e1af4baa647b0981e433b7dc364cbcc17adfc97d2bbbe3b4246d5d106983b89a7e19ca0086e3e99119dc84348cd",
          "sha256": "9c471aac020a0b962a2daaed7de599c8d7be5bfda9beefb74b78d3fae942a390",
          "sha1": "0f276e8d9f657b4d2793209b987e89d49490258e",
          "md5": "bf6650dac40815a250f7b7995314dfe7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libraryB-1.2.aar",
          "url": "libraryB-1.2.aar",
          "size": 23421,
          "sha512": "5bcb453c56dc159e37a1e0804f22175961786e1af4baa647b0981e433b7dc364cbcc17adfc97d2bbbe3b4246d5d106983b89a7e19ca0086e3e99119dc84348cd",
          "sha256": "9c471aac020a0b962a2daaed7de599c8d7be5bfda9beefb74b78d3fae942a390",
          "sha1": "0f276e8d9f657b4d2793209b987e89d49490258e",
          "md5": "bf6650dac40815a250f7b7995314dfe7"
        }
      ]
    }
  ]
}
